### ISSUE TITLE
only updates the license for 100 sites

### ISSUE THREAD

**Issue by almostdaniel** [samuelaguilera/sar-update-gravity-forms-license-networkwide#1]
Not all my sites were being updated. 

I did some hunting and discovered that the [get_sites() function](https://developer.wordpress.org/reference/functions/get_sites/) defaults to returning 100 sites. The number of sites returned is controlled by the 'number' argument. Setting this argument to '0' will retrieve all sites in a network.

Here's the line of code in question:

https://github.com/samuelaguilera/sar-update-gravity-forms-license-networkwide/blob/2371ad9324b656d12beca9513660395d545d03a3/sar-update-gravity-forms-license-networkwide.php#L64

I modified my code to the following and I was able to update all 300+ sites in my network:

`
$blog_ids = get_sites( array( 'fields' => 'ids', 'number' => '0' ) ); // Return only blog_id for each site of the network
`

I'll try to put together a pull request.

**Comment by samuelaguilera** [comment]
@almostdaniel Thanks for the suggestion Daniel, no need to make the pull request, I'm going to commit the change just after this comment.

**Comment by almostdaniel** [comment]
Great!
